### ISSUE TITLE
Improve uli command for drush aliases

### ISSUE THREAD

**Issue by shelane** [docksal/addons#26]
In its current iteration, uli only seems to work on the local default site. This doesn't help a multisite setup or trying to access the site on the dev, stage, or live server. Even if it would seem out of order, I would like to be able to pass in the alias and be able to pass in uli parameters:

`fin uli @mysite.live siteadmin`

The command would then need to discover that there is an alias present and modify the request to be: `drush @mysite.live "$@"`

**Comment by achekulaev** [comment]
Doesn't it work right now? `fin uli @alias` ?

**Comment by shelane** [comment]
`fin uli @mysite.live` 
results in:
`https://mysite.docksal/user/reset/1/1530812398/snSlKSEyycC6FBSrr9liclERX10_CHJZGkDXJXGI63c/login`

I expect:
`https://mysiteurlfromalias/user/reset/1/1530812398/snSlKSEyycC6FBSrr9liclERX10_CHJZGkDXJXGI63c/login`

The command is currently `fin drush uli "$@"`. You really can't just make it `fin drush "$@" uli` to accept the alias (which that does) because then you loose the ability to pass additional uli arguments.

**Comment by frederickjh** [comment]
At first I was not sure which aliases we were talking about, as both Drush and Fin have them. 

It looks to me after looking at the code that the aliases we are talking about are Drush site aliases not Fin development site aliases.

So, @shelane is right we cannot just change the order. The command will work without a Drush site alias or arguments on  on a Drupal site whose folders you are inside, simply `fin uli`. 

If a Drush site alias is used, it should come after `drush` to tell it what site to work on. The options that `uli` accepts should come after it.

  The code needs restructured so that it looks to see if a Drush site aliases is given on the command line then places this after `drush` and before the Drush command `uli`. Then all other given options could be dumped at the end to be processed.

**Comment by frederickjh** [comment]
@shelane I have push a [new branch to my fork](https://github.com/topdroplabs/addons/tree/feature/uli-addon--29-http-and-https-links--26-improve-for-drush-aliases) that I believe fixes this issue and issue #29. 

As I do not use Drupal multi-site I do not have any Drush site aliases setup to test with. Can you please test this code?

You will need to put the contents of the `uli` folder in one of your projects `.docksal/addons/uli folder to test. Documentation has also been updated.
Thanks!

**Comment by shelane** [comment]
Yes, it worked great... Can I make two other suggestions that should be very easy?

Add to the comments a Usage statement showing the options? You have the "Add -s" but something like:
```
## Usage fin uli @drushalias -s
## The drush alias and -s flags are optional
```

Second, can you add a -o option that would then run an "open" command on the $uli value?
`open $uli`
I don't know if Linux or Windows has an equivalent, but it's nice on the Mac for it to automatically open the url in my default browser.

**Comment by frederickjh** [comment]
@shelane I have added your comments to the file, however they will not be shown on the fin help screen. Only the first comment line is shown there. As far as I know they will only be seen by those that open the `uli` file to read them. I have also added to the README.md that they are optional.

> Second, can you add a -o option that would then run an "open" command on the $uli value?

Does the --browser option that `drush uli` accepts not work?  Try adding something like this to your command.
`--browser=firefox`
If this works you can add this option to a drush configuration file so that it always uses this option when you run the command. See the [example.drush.yml](https://github.com/drush-ops/drush/blob/master/examples/example.drush.yml) file and the [section on command-specific options](https://github.com/drush-ops/drush/blob/master/examples/example.drush.yml#L90) for examples of how to do this.

See the [`drush uli` documentation](https://drushcommands.com/drush-9x/user/user:login/) for more details about the options it accepts.

**Comment by shelane** [comment]
The additional comments show when you run `fin help uli`.

**Comment by frederickjh** [comment]
Ah, yes you are correct. 
I had removed my symlink (.docksal/addons/uli) that I used for testing, earlier today. That is why I did not see it when I tested `fin help uli` before.
